<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7116b436-c6cc-41bc-a542-3ef3e4ada080</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App1.ApiService\App1.ApiService.csproj" />
    <ProjectReference Include="..\App1.Web\App1.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.1" />
  </ItemGroup>

</Project>
